### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Polurival** [argyle-systems/argyle-plugin-android#15]
Fatal Exception: java.lang.NullPointerException: account must not be null
       at com.argyle.ui.features.common.e.invoke(SourceFile:6)
       at com.argyle.ui.features.common.a$c.onChanged(:2)
       at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:171)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at com.argyle.ui.features.search.SearchFragment.j(SourceFile:32)
       at com.argyle.ui.features.search.SearchFragment.onViewCreated(SourceFile:3)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:227)
       at android.os.Looper.loop(Looper.java:330)
       at android.app.ActivityThread.main(ActivityThread.java:8074)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:579)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by Varnius** [comment]
@Polurival this should've been fixed with `5.4.0`, so I'm closing the issue. Feel free to open a new one if you encounter problems.
